### ISSUE TITLE
Heavy Zoteling freezes after 0 or more jumps

### ISSUE THREAD

**Issue by nQvTgLrp** [Hoo-Knows/hk-challenge-mode#1]
I did some debugging. It was stuck at state "Dr". But I didn't find out the root cause though.

**Comment by Hoo-Knows** [comment]
Let me know if this fixes the issue:
[ChallengeMode.zip](https://github.com/Hoo-Knows/HollowKnight.ChallengeMode/files/9080857/ChallengeMode.zip)

**Comment by nQvTgLrp** [comment]
Yeah. This fixes the bug for me. I am curious how did you fix it.

**Comment by Hoo-Knows** [comment]
It was accessing the transform of an FSM instead of a GameObject during the check for what direction to jump in.
